import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles((theme) => ({
  body: {
    backgroundColor: "#fafafa",
    margin: 0,
    padding: 0,
    color: "#2d3436",
    fontFamily: '"Roboto", sans-serif',
  },
  layout: { display: "flex", alignItems: "stretch", minHeight: "100vh" },
  sidebarMenu: {
    textAlign: "center",
    alignItems: "center",
    background: "white",
    bottom: "0",
    padding: "15px 0px 10px 0px",
    width: "300px",
    overflow: "hidden",
  },
  profilePic: {
    marginTop: "30px",
    width: "5em",
    border: "none",
    borderRadius: "50%",
    transition: "all 0.3s",
    "&:hover": { boxShadow: "1px 3px 12px 0px rgba(0, 0, 0, 0.45)" },
  },
  displayName: {
    margin: "0",
    marginTop: "10px",
    fontSize: "2em",
    fontWeight: "600",
    color: "#4834d4",
  },
  subtitle: { margin: "0px 0px 5px 0px" },
  menuItems: {
    marginTop: "40px",
    marginBottom: "20px",
    width: "100%",
    "a:hover": {
      borderLeft: "5px solid #4d00ff",
      background: "rgba(77, 0, 255, 0.11)",
    },
  },
  inactiveItem: {
    padding: "20px 0px 20px 20px",
    width: "100%",
    textAlign: "left",
    display: "inline-block",
    color: "black",
    background: "rgba(0, 0, 0, 0.03)",
    transition: "all 0.3s",
    textDecoration: "none",
  },
  activeItem: {
    padding: "20px 0px 20px 20px",
    width: "100%",
    textAlign: "left",
    display: "inline-block",
    color: "black",
    background: "rgba(77, 0, 255, 0.08)",
    transition: "all 0.3s",
    textDecoration: "none",
    borderLeft: "2px solid #4d00ff",
  },
  signout: {
    width: "100%",
    height: "40px",
    background: "#4834d4",
    color: "white",
    border: "none",
    borderRadius: "5px",
    transition: "all 0.3s",
    cursor: "pointer",
    "&:hover": { background: "rgba(95, 15, 255, 0.76)" },
  },
  dashboardView: { margin: "40px", flex: "5 5 calc(100vw - 300px)" },
  viewHeading: { fontSize: "2em", fontWeight: "600" },
}));
